### ISSUE TITLE
Support to supress elm-format's error output

### ISSUE THREAD

**Issue by juanedi** [jcollard/elm-mode#117]
When using flycheck, introducing a syntax error results in having repeated error reports (with a multiline `message` popping up which at least for me is a bit annoying).

<img width="889" alt="screen shot 2017-09-30 at 05 56 15" src="https://user-images.githubusercontent.com/753421/31044375-a239f21c-a5a4-11e7-955f-bdaa700c72ea.png">

I believe it's good to have some notification that `elm-format` failed, but unless there's an installation problem (binary not found or something like that), we can probably expect most (almost all!) failures in calls to `elm-format` to be caused by syntax errors, which will be caught by flycheck or any other compilation method used.

Would it make sense to introduce something like this?

```emacs-lisp
(defcustom elm-format-display-full-errors t
  "If set, display output of failed calls to elm-format."
  :group 'elm-format
  :type 'boolean)
```

We could keep it enabled by default to preserve current behavior. If not set, we could show a one-liner message like "Failed to format current buffer. Enable elm-format-display-full-errors for more information.". This way we could avoid duplicating error messages without swallowing all errors.

I'd be happy to send a PR for this, just wanted to check if it sounds good to you all.

Thanks!

**Comment by purcell** [comment]
I agree that something like this would be helpful. `elm-format` doesn't make a great compiler, and the pop-up messages aren't very helpful. However calling `elm-format` directly (rather than when it is called automatically on save) should arguably display these errors prominently. The fix might therefore be slightly more fiddly, but I'd be happy to receive a PR. I'd probably suggest a scheme like the following:

- The output of `elm-format` always get sent to an `*elm-format errors*` buffer.
- When `elm-format` succeeds, then `(message "elm-format applied")`
- When it fails on save, then call `(message "elm-format failed: see *elm-format errors*")`
- On other failures, call `display-buffer` on the errors buffer to pop it up.

**Comment by juanedi** [comment]
I love that solution! I'll give it a try 😄
