### ISSUE TITLE
Go to definition

### ISSUE THREAD

**Issue by TheHeartmann** [jcollard/elm-mode#133]
Hey! I've been toying around with it a bit, and there's some great stuff here, but unless I've glossed over something I'm missing a 'go to definition' functionality. Is this something that the package should provide, and if so, is it in the works, or do I need to go elsewhere for that?

**Comment by purcell** [comment]
The README covers how to get this using TAGS support. There's no alternative currently.

**Comment by purcell** [comment]
The issue is that the completion is provided by `elm-oracle`, which works using a pre-built database of the functions in downloaded Elm packages. It doesn't understand the local code at all, so you won't get completion of local symbols, sorry.

That said, I think it might be possible to build support for such completion, though it'd be a bit of work, so I haven't tackled it yet -- I'm writing much more Haskell than Elm currently. :-)
