### ISSUE TITLE
Completion for user defined bindings on same file

### ISSUE THREAD

**Issue by vitorqb** [jcollard/elm-mode#134]
Hello and thanks for the nice work on elm-mode :).

I have recently installed elm-mode and I'm using it with company-mode. I currently have nice completions for binds from imported modules, but I have no completion whatsoever for variable binds in the same file. I was reading #124 and I think this might be because  elm-oracle does not parse bindings from the same file.

I was wondering if you know any way to overcome this issue. I know that there is currently no nice way to get the _type_ of the binds, but I was wondering if there is any way to at least get completion for the variable names (without type signatures).

Thanks!

**Comment by purcell** [comment]
Yes, this is certainly related, and is indeed because `elm-oracle` only knows about symbols in installed packages. Approaches to address this could include:

- Building a set of known exported bindings in all open Elm files
- Performing searches on demand for referenced modules, and then identifying exported symbols
- Waiting for upstream tool support that I believe Evan has been talking about building

Of these, the last one is the most likely to happen, unless someone steps up to try one of the other approaches.

**Comment by vitorqb** [comment]
@purcell Thanks for the answer. I wished I knew enough of elm/elisp to help (hopefully I will some day). I ended up using `company-dabbrev-code-modes` to at least get some completion for the symbols. Works fine enough for me.

Feel free to close the issue if you want.

**Comment by theothornhill** [comment]
I am guessing this can be closed since lsp is a thing now?

**Comment by purcell** [comment]
Yep!
