### ISSUE TITLE
Indentation is weird when writing multi-lines lists

### ISSUE THREAD

**Issue by gabriel-dehan** [jcollard/elm-mode#45]
I am pretty new to Elm but the identation is seemingly not working properly in this case :

![elm](https://cloud.githubusercontent.com/assets/1383633/11571925/0cb91702-99ff-11e5-8b54-d579d3e56763.png)

Any clue on how to fix that ?

**Comment by Bogdanp** [comment]
The indentation code tends to add a new level on `newline-and-indent`. Please see the `README` note about indentation cycling. The gist of it is, every time you get an indentation level you don't expect you should be able to get the one you want simply by hitting tab.

Based on your screenshot, you might also be having issues because your usage of `,` is somewhat non-standard. The indenter would've worked better had you formatted your lists like this:

```elm
div [ id "container ]
  [ pageHeader
  , entryList
  , pageFooter
  ]
```

Hope that helps! Let me know if any of this is confusing and I'll try to explain it better :)

**Comment by roobie** [comment]
I think this is the same issue I am having when I move code between buffers.

Example:

this is the starting point:
```
dock = foldp updateDocks Dict.empty ships
```

I want to move these lines from one buffer to the one above (i.e. kill then yank)
```
port coordinates  : (Int,Int)
port incomingShip : Signal { name:String, capacity:Int }
port outgoingShip : Signal String
```

I will now paste these three lines of code below the first line:

```
dock = foldp updateDocks Dict.empty ships

       port coordinates  : (Int,Int)
                           port incomingShip : Signal { name:String, capacity:Int }
                                               port outgoingShip : Signal String
```

Marking the region and executing `indent-region` seems to cause the same issue.

**Comment by Bogdanp** [comment]
> I want to move these lines from one buffer to the one above (i.e. kill then yank)

This is not standard behavior. Your setup must be calling `indent-region` after inserting the text. If you use spacemacs make sure you add `elm-mode` to `spacemacs-indent-sensitive-modes`.

> Marking the region and executing indent-region seems to cause the same issue.

The way we handle indentation right now makes indenting a region that contains multiple top-level definitions particularly problematic because, like I mentioned above, we tend to add a new level on each line and we don't distinguish between top-level definitions and everything else. I would say that if you want to use indent region try to limit yourself to one such definition at a time.

**Comment by Bogdanp** [comment]
I'm closing this for now. Feel free to re-open it if you have any other questions.
