### ISSUE TITLE
Question: Displaying Ansi colors

### ISSUE THREAD

**Issue by Soreine** [jcollard/elm-mode#98]
I often use `C-c C-c` to compile my project, but the result buffer contains Ansi color codes that my Emacs does not support:

```
Compilation started at Thu Mar  9 10:37:44

elm-make main.elm --yes --warn --output=elm.js
[36m-- SYNTAX PROBLEM ----------------------------------------------------- main.elm
```

How do you guys configure your Emacs to properly show the command-line output of the compilation?

I have found I could use Ansi Color, and define an interactive function as described here http://stackoverflow.com/questions/23378271/how-do-i-display-ansi-color-codes-in-emacs-for-any-mode

But how do I apply this mode every time I run `C-c C-c` ?

Thank you for the awesome mode.

**Comment by juanedi** [comment]
Similar problem here.

I have the package set up so `elm-format` is run every time I save a file. If I introduce a syntax error the output's colors are not shown, and I see those escape sequences.

 @Soreine did you find a workaround?

**Comment by Soreine** [comment]
I haven't, unfortunately.

**Comment by juanedi** [comment]
Just submitted a PR that fixes the problem for the formatter's output. This won't work for compilation, since for that case emacs' compilation buffer is used instead of a message.

Still, I think I found a woraround for @Soreine's problem. This should hook into the compilation process and colorize the text in the output buffer ([source](http://stackoverflow.com/questions/3072648/cucumbers-ansi-colors-messing-up-emacs-compilation-buffer#3072831))

```
(require 'ansi-color)
(defun colorize-compilation-buffer ()
  (let ((inhibit-read-only t))
    (ansi-color-apply-on-region (point-min) (point-max))))
(add-hook 'compilation-filter-hook 'colorize-compilation-buffer)
```

I tried it an seems to work just fine, although it would probably be a bit intrusive to add this to the package's code. Not sure, emacs newbie here :-)
